### PR TITLE
[MRG] - Update website theme to match SORSE brand

### LINKED ISSUE #167: Match colour scheme with Logo
Now that we have a logo, tweak some of the colours to match.

Also, bear in mind accessibility as in #47 

[ ] header
[ ] links
[ ] buttons

### PR DESCRIPTION
**Pull request by trallard**
This PR closes #167.

Overall it provides consistency across:
- Buttons
- Links
- Header
- TOC & sidebar

Made changes to the fonts as well to provide a more consistent look

Also been running the site through `pa11y` to ensure everything is accessible.

### CODE REVIEW

**Comment by Chilipp** [comment]
hey @trallard! Thank you very much for your input here! I am definitely not the right person to judge about colors and stuff, but I propose some technical things in #214. I did not push it to your branch here, as I am not an expert on CSS and color-coding.

@eileen-kuehn, as you have a better feeling for this, would you mind having a look? Otherwise I am okay with merging it

**Comment by Chilipp** [comment]
one comment: personally I find the font a bit difficult to read, and as we use a different font for the menu and stuff, I am not sure whether we should change this in the body. Or is this common practice @trallard?

**Comment by trallard** [comment]
I just thought the previous font looked slightly odd but can revert and see if that makes it easier to read. I am not privy about it so will make the changes (incorporating the other merged PR first tho).

**Comment by Chilipp** [comment]
sounds good! Shall I make a quick poll afterwards within our committee slack channel?

**Comment by trallard** [comment]
Ok so I have made some changes: 

- [bd9a930](https://github.com/SORSE/sorse.github.io/pull/212/commits/bd9a9304278479e3482aaed6f327d6d30ec1b754) & [
8db5022](https://github.com/SORSE/sorse.github.io/pull/212/commits/8db5022a7c7138115aa67ced665f959bea07c37b) ensure that the Title font is actually the new  Google font **
- [7ebff71](https://github.com/SORSE/sorse.github.io/pull/212/commits/7ebff71348c428aa28345042b1fce85e8b7b9aba)


Funnily enough (and since I have never used this. theme) I just realised that it uses system font stacks so the fonts were indeed never changed (my bad! see <https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#font-stacks>) this should now work. I left the body font unchanged and only applied changes to the heading font @Chilipp 


This *should* now complete this styling PR

**Comment by Chilipp** [comment]
LGTM. I'd like to have the feedback of @eileen-kuehn on https://439-267395254-gh.circle-artifacts.com/0/SORSE/index.html and otherwise we can merge this. Thanks a lot @trallard!

**Comment by ClaireWyatt** [comment]
Looks gawgess (gorgeous)!

**Comment by Chilipp** [comment]
thanks @eileen-kuehn!

> The hover style of buttons in the footer prevents visibility of icons, icons nearly have the same color then

Just for clarification: So you mean the background of the _Report issue_ button in the screenshot below should be darker?

image

**Comment by trallard** [comment]
I checked all the colour combinations for accessibility - that particular combination gives a 5.92AA contrast <https://colorable.jxnblk.com/ffffff/646464> I can always decrease the lightness but then it would be too close to the default button shade. 

Either way let me know

**Comment by Chilipp** [comment]
alright, thanks @eileen-kuehn! I just made a minor fix to the buttons layout on focus with 71e78c3, and merge this when the CI finishes.

**Comment by Chilipp** [comment]
thanks a lot @trallard for your help here :partying_face:

**Pull request merged**
