### PR TITLE
Add Tania Allard to the committee members

### PR DESCRIPTION
**Pull request by Chilipp**
This PR adds Tania Allard as a member of the website committee

see https://github.com/SORSE/sorse.github.io/issues/167#issuecomment-652372464

see https://420-267395254-gh.circle-artifacts.com/0/SORSE/contact/committees/index.html#website for a preview

@trallard: A profile pic is still missing (but it is not obligatory). If you are happy with the information displayed, please approve this PR and we merge it

### CODE REVIEW

**Comment by trallard** [comment]
Here is the link to the profile picture: <https://res.cloudinary.com/nezahualcoyotl/image/upload/v1593696663/Tania_Allard19-07-170433_rth3dj.jpg> 

This LGTM!

**Comment by Chilipp** [comment]
alright, thanks @trallard! I uploaded it with bbecc40. If you are happy with the [result](https://442-267395254-gh.circle-artifacts.com/0/SORSE/contact/committees/index.html#website), please review and approve this PR.

**Comment by Chilipp** [comment]
or is _LGTM_ already you're approvement? sorry, we have the policy that every PR needs at least one approving review to merge it (although I can merge it, if you just say it's ok)

**Comment by trallard** [comment]
Done! I realized I never sent the approval 😅

**Pull request merged**
