### PR TITLE
Add events schedule

### PR DESCRIPTION
**Pull request by Chilipp**
This WIP implements the basis for showing events on the website. For this purpose we add an `_events` collection, 

- each event is assigned to a specific category (e.g. Software demo, talk, etc.). 
- each event does have a `date` attribute that is supposed to show the date and time of the event and can be used to be displayed in the schedule and the upcoming events.
- the upcoming events should be on the [front page](http://www.philipp-s-sommer.de/sorse.github.io/#upcoming-events)
- the full schedule of events should be on the [/programme/](http://www.philipp-s-sommer.de/sorse.github.io/programme/) page

I plan to create a custom layout for event pages, such as I did for the `_bazaar` collection, to show all the authors, date, etc.. Currently it only uses the default `single` layout.

@vsoch:

- how shall we display the upcoming events? Looking at the docs of [fullcalendar.io](https://fullcalendar.io/), I could not find a useful function for it. We could show the events within the current week, but I don't think this is the best approach
- can we actually filter the events on the calendar? E.g. to only display events of a specific category?

The rendered webpage of this PR can be seen at http://philipp-s-sommer.de/sorse.github.io

### CODE REVIEW

**Comment by vsoch** [comment]
Not a month view? https://fullcalendar.io/docs/month-view

**Comment by Chilipp** [comment]
I thought about having a month-view on the `/programme/` page, but for the front page only the next 5 upcoming events, or so

**Comment by ClaireWyatt** [comment]
sounds great!

**Comment by vsoch** [comment]
@Chilipp I don't think I can get this working, the minimal mistakes compiles jquery into their base so we would have to customize it to include the calendar libraries too - and then they would be included on every page. I think it's overkill, and a drawback to the theme (it's worked on two other themes I tested without issue).

**Comment by Chilipp** [comment]
Hmm, ok, sounds weird. Can you put the code in GitHub? Then I'll have a look at it later this evening, too

**Comment by Chilipp** [comment]
This PR is already quite far, but we have to do some layout issues first (e.g. displaying the different categories with different styles). For this purpose however, I'd like to wait until #212 is merged

**Comment by Chilipp** [comment]
closing this in favor of the add/events branch

**Pull request closed without merging**
