### PR TITLE
Recording widget in events if available

### PR DESCRIPTION
**Pull request by eileen-kuehn**
This PR adds a recording widget at the bottom of the events detail page if a `recoding_url` from *youtube* is available. The widget supports adding a specific timestamp to allow for recording of several contributions.

### CODE REVIEW

**Comment by Chilipp** [comment]
Thanks a lot @eileen-kuehn! Looks fantastic :smiley:

Just a minor thing: I'd put the widget between author list and times, don't you? Down below we have all the supplementary buttons, I'd think the recording as part of the content

**Comment by eileen-kuehn** [comment]
> Just a minor thing: I'd put the widget between author list and times, don't you? Down below we have all the supplementary buttons, I'd think the recording as part of the content

I'd prefer having it below the abstract as I first want to read if it is worth watching (what it is for sure!).

**Comment by Chilipp** [comment]
Alright, fine with me! Thanks :)

**Review by Chilipp — APPROVED** [review]
LGTM :smiley:

**Pull request merged**
