### PR TITLE
Events for round 5

### PR DESCRIPTION
**Pull request by eileen-kuehn**
This PR includes the events from the 5th round.

Please note, we have our first panel. Is there already defined how the information for *panelists* will be rendered? I included them now as a list.

### CODE REVIEW

**Comment by eileen-kuehn** [comment]
@catsmith, please go ahead adding any additional information.
Please ping me, if I can already create some of the indico events.

@Chilipp, please let me know, if I should change the export of the panelists.

**Comment by Chilipp** [comment]
> Please note, we have our first panel. Is there already defined how the information for panelists will be rendered? I included them now as a list.

nope, not yet. We could implement them as a table, something like

|  Panelists |
|---|
| Alys Brett is Head of the Software Development Group at UKAEA and has coordinated the national RSE involvement in SCRC (Scottish COVID-19 Response Consortium), which is part of the broader Royal Society RAMP call to action. She has first-hand experience of quickly establishing projects that brought together RSEs and modellers from different backgrounds. |
| Dr. Richard Reeve is co-director of the Boyd Orr Centre for Population and Ecosystem Health at the University of Glasgow and leads the modelling work of SCRC as a joint founder. As an academic researcher who also advocates within the RSE community, he offers a bridging perspective between RSEs and researchers and why their relationship is so important for projects like this. |
| Dr. Christopher Woods is EPSRC RSE Fellow at the University of Bristol's Advanced Computing Research Centre and got involved in the MetaWards project near the beginning of the pandemic. Chris took a unique and well-documented approach of adopting the existing code and translating it into Python, which proved to be an effective way of building trust in the original software. |
| Dr. Lilith Whittles is a Postdoctoral Researcher at the Department of Infectious Disease Epidemiology, Imperial College. Currently, she is applying her expertise in the mathematical modelling of disease transmission to the real-time modelling of the COVID-19 epidemic, working closely with RSEs to achieve this goal. |
| Dr. Rich Fitzjohn runs the RESIDE group (Research Software for Infectious Disease Epidemiology) at Imperial College. He collaborated with Dr. Whittles directly to support the development of her model. His group has worked with epidemiologists in the MRC Centre for Global Infectious Disease Analysis for the last 5 years, including the response to previous Ebola outbreaks. |

or maybe add them with a details tag like

### Panelists
<details>
<summary>Alys Brett</summary>
Alys Brett is Head of the Software Development Group at UKAEA and has coordinated the national RSE involvement in SCRC (Scottish COVID-19 Response Consortium), which is part of the broader Royal Society RAMP call to action. She has first-hand experience of quickly establishing projects that brought together RSEs and modellers from different backgrounds.
</details>

<details>
<summary>Dr. Richard Reeve</summary>
Dr. Richard Reeve is co-director of the Boyd Orr Centre for Population and Ecosystem Health at the University of Glasgow and leads the modelling work of SCRC as a joint founder. As an academic researcher who also advocates within the RSE community, he offers a bridging perspective between RSEs and researchers and why their relationship is so important for projects like this.
</details>

<details>
<summary>Dr. Christopher Woods</summary>
Dr. Christopher Woods is EPSRC RSE Fellow at the University of Bristol's Advanced Computing Research Centre and got involved in the MetaWards project near the beginning of the pandemic. Chris took a unique and well-documented approach of adopting the existing code and translating it into Python, which proved to be an effective way of building trust in the original software.
</details>

<details>
<summary>Dr. Lilith Whittles</summary>
Dr. Lilith Whittles is a Postdoctoral Researcher at the Department of Infectious Disease Epidemiology, Imperial College. Currently, she is applying her expertise in the mathematical modelling of disease transmission to the real-time modelling of the COVID-19 epidemic, working closely with RSEs to achieve this goal.
</details>

<details>
<summary>Dr. Rich Fitzjohn</summary>
Dr. Rich Fitzjohn runs the RESIDE group (Research Software for Infectious Disease Epidemiology) at Imperial College. He collaborated with Dr. Whittles directly to support the development of her model. His group has worked with epidemiologists in the MRC Centre for Global Infectious Disease Analysis for the last 5 years, including the response to previous Ebola outbreaks.
</details>

**Comment by Chilipp** [comment]
I think I'd prefer the table. We could also list them that way in the PDF.

**Comment by eileen-kuehn** [comment]
@Chilipp, from my side of view the files are complete now. 
What about the tables? I can have a look at the implementation this evening or is it done already?

**Comment by Chilipp** [comment]
No, also in my to-do list for this evening. We need to adjust the events layout and the PDF template. If you have a couple of minutes to invest, that would be great :) then I can focus on the other two issues that came up today

**Comment by eileen-kuehn** [comment]
@Chilipp, panelists are no tabular data, so I currently tend not to display them like this. For a first try I only used a simple list that we can still improve on. What do you think?

We might consider something like [Accordions](https://semantic-ui.com/modules/accordion.html)?

Screenshot 2020-11-30 at 18 35 09

**Comment by Chilipp** [comment]
Sounds good to me @eileen-kuehn

**Comment by Chilipp** [comment]
@eileen-kuehn, what's your progress on this? I might be able to spend some time this evening.

**Comment by eileen-kuehn** [comment]
@Chilipp, ah sorry, didn't get from your response that you wanted the accordion ;)
Today are way too many meetings, so that I cannot spent time today. If you could have a look this evening, this would be awesome. Otherwise I can takeover tomorrow.

**Comment by eileen-kuehn** [comment]
I would propose merging this in a first step and taking care of another ticket to implement visual improvements.

**Review by Chilipp — APPROVED** [review]
alright, I adapted the latex template, so let's merge this.

**Pull request merged**
