### PR TITLE
Add add-to-calendar-button

### PR DESCRIPTION
**Pull request by Chilipp**
As discussed in #216, we'd like to add an _Add to calendar_ button to the event pages. This PR is using the [Add-to-Calendar button by addevent.com](https://www.addevent.com/documentation/add-to-calendar-button) and applies some custom styling to show it on our webpage.

@vsoch: the add-to-calendar button you mentioned in https://github.com/SORSE/sorse.github.io/issues/216#issuecomment-653906840 seems quite outdated and hasn't received a commit since 2018. So I looked around a bit and found this library. Do you think, that's ok?

here is an example: https://549-267395254-gh.circle-artifacts.com/0/SORSE/programme/workshops/event-004/index.html

### CODE REVIEW

**Comment by Chilipp** [comment]
Just saw. It works locally, but when you want to use it online, you need to pay for addevent.com. So closing this...

**Comment by Chilipp** [comment]
I can look for another alternative tomorrow.

**Comment by vsoch** [comment]
You beat me to it! I just was testing and saw this:
image

What a bummer, it looked really great.

**Comment by Chilipp** [comment]
@vsoch: What do you think about using https://github.com/commonpike/add-to-calendar-buttons ([example][example])? It's a fork of the one you initially posted, but nicer and more like the stuff I did want to implement in this PR (I can actually use the files from this PR! see [method 2 from the README](https://github.com/commonpike/add-to-calendar-buttons#method-2)).

Seems like there is no up-to-date package available via npm, or so, so I'd make a fork into the SORSE organization and use the js files from there, i.e. something like

```html
<script src="https://raw.githubusercontent.com/SORSE/add-to-calendar-buttons/master/add-to-calendar.min.js"></script>
```

this way, we could still have it under version control and eventually easily update from upstream. An alternative to downloading from `raw.githubusercontent.com` would be to add the fork as a submodule to the [assets][assets]/js folder.

What do you think?

[example]: https://commonpike.github.io/add-to-calendar-buttons/example.html
[assets]: https://github.com/SORSE/sorse.github.io/tree/master/assets

**Comment by vsoch** [comment]
It would definitely be worth a shot! If we are going to use our version for the site (the fear is losing the one on GitHub?) it would make most sense to package with this repository with assets (second suggestion) so we don't misleads others into thinking we are maintaining it.

**Comment by Chilipp** [comment]
> (the fear is losing the one on GitHub?)

yes, forks disappear from time to time. So you say, we should not make a fork? I see your point. It's just more convenient to look what changed in the original repository at https://github.com/commonpike/add-to-calendar-buttons when they implement striking new features, for instance. They unfortunately do not have a release management

**Comment by vsoch** [comment]
Hmm I didn’t think about that, and I definitely agree. If you are worried about being able to update from this upstream, then it wouldn’t hurt to make a fork.

**Pull request closed without merging**
