### PR TITLE
Twitter fix

### LINKED ISSUE #189: Issue with SORSE
_pages/home.md

website logo not appearing on the twitter feed when linked to the website in a tweet. 

https://brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/#tldr-too-long-didnt-read

### PR DESCRIPTION
**Pull request by Chilipp**
twitter meta information are only inserted in the head, if twitter.username is set. see https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html

closes #189

@ClaireWyatt could you please test with https://346-267395254-gh.circle-artifacts.com/0/SORSE/index.html and [the validator tool](https://brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/#use-the-validator-tool) whether that works?

### CODE REVIEW

**Comment by TeriForey** [comment]
I still see the grey image using the validator tool and the link you provided

**Comment by ClaireWyatt** [comment]
me too. I stil see the grey box and paper scroll.

**Comment by Chilipp** [comment]
does twitter maybe have a problem with the banner being `.svg`?

**Comment by Chilipp** [comment]
because the meta information are there in https://346-267395254-gh.circle-artifacts.com/0/SORSE/index.html

```html
  <meta name="twitter:site" content="@Int_SORSE">
  <meta name="twitter:title" content="SORSE">
  <meta name="twitter:description" content="International Series of Online Research Software Events">
  <meta name="twitter:url" content="https://346-267395254-gh.circle-artifacts.com/0/SORSE/">

  
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="https://346-267395254-gh.circle-artifacts.com/0/SORSE/assets/images/sorse-banner.svg">
```

**Comment by Chilipp** [comment]
from https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image

> twitter:image
>
> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

**Comment by Chilipp** [comment]
@ClaireWyatt or @TeriForey: Could you please try again with https://349-267395254-gh.circle-artifacts.com/0/SORSE/index.html?

**Comment by TeriForey** [comment]
It looks good to me! 
Screenshot 2020-06-25 at 13 14 21

**Comment by Chilipp** [comment]
great, thanks @TeriForey! can you also check another page, https://350-267395254-gh.circle-artifacts.com/0/SORSE/programme/call-for-contributions/index.html for instance? I don't have a twitter account, sorry

**Comment by TeriForey** [comment]
There's more text so it's only showing the centre of the image - I still think this looks okay though. 

Screenshot 2020-06-25 at 13 20 08

**Comment by Chilipp** [comment]
this is set by the og_image in _config.yml. shall we use the logo here?

https://github.com/SORSE/sorse.github.io/blob/7775f44a461cd1a0d148e610d20087a4918f351b/_config.yml#L18

shall we use the logo here?

image

**Comment by TeriForey** [comment]
Try it and I'll take a look at how it looks

**Comment by Chilipp** [comment]
alright: here is the new version: https://351-267395254-gh.circle-artifacts.com/0/SORSE/programme/call-for-contributions/index.html

**Comment by TeriForey** [comment]
Same problem, in fact now it's worse because it's a lower res!

Screenshot 2020-06-25 at 13 28 46

**Comment by Chilipp** [comment]
hmm, I see. It needs to be quadratic...

**Comment by Chilipp** [comment]
this should work now

https://352-267395254-gh.circle-artifacts.com/0/SORSE/programme/call-for-contributions/index.html

sorry, I am in a workshop, so everything takes a while :wink:

**Comment by TeriForey** [comment]
Screenshot 2020-06-25 at 13 54 31

Looks good!

**Comment by Chilipp** [comment]
alright. Feel free to approve and merge this PR if you like

**Pull request merged**
