### PR TITLE
add logo to the website

### LINKED ISSUE #16: Add logos for the website
We need a logo for the SORSE20 webpage

- [x] favicon added (for the window title)
- [x] logo added (for the navigation menu bar at the top)

### PR DESCRIPTION
**Pull request by Chilipp**
this PR adds the logos designed by @trallard to the website. I also made the front page a splash screen and it looks like in the screenshot below (or see https://290-267395254-gh.circle-artifacts.com/0/SORSE/index.html). I am not so much in favor of the color of the masthead (it is set in

https://github.com/SORSE/sorse.github.io/blob/0e1b26563565477470ce07ec321fdda9c0f58f54/assets/css/main.scss#L12-L14

but I cannot use the colors of tanja logo because this would not work with having the logo in the masthead.

image

closes #16

### CODE REVIEW

**Comment by Chilipp** [comment]
we should acknowledge @trallard for the logo on the website. Any idea where? maybe in the footer?

image

**Comment by TeriForey** [comment]
Footer seems a good place for the acknowledgement. 

Can you change the background of the splash screen to black? There's a dark grey border appearing when the image doesn't fit.

**Comment by Chilipp** [comment]
@eileen-kuehn and @TeriForey. are you okay with this setup?

**Comment by Chilipp** [comment]
alright, @trallard, you have been acknowledged with a link to your github account. Thanks a lot for your help!

https://310-267395254-gh.circle-artifacts.com/0/SORSE/index.html

image

**Pull request merged**
