### PR TITLE
Removed border-radius on author avatar

### LINKED ISSUE #133: delete round corners in topic bazaar logo
delete round corners in topic bazaar logo and set min-width a bit wider

example at 
https://rse-leaders.github.io/SORSE20/programme/bazaar/rse-in-the-digital-humanties-domain/

>@Chilipp hmm, das mit der Rundung ist nicht so schön, da muss ich den Style von minimal mistakes für diese eine Seite überschreiben

image

### PR DESCRIPTION
**Pull request by TeriForey**
closes #133

### CODE REVIEW

**Comment by florianthiery** [comment]
maybe also a bit wider in width?

**Comment by Chilipp** [comment]
feel free to merge this when you are both happy, @florianthiery and @TeriForey

**Comment by TeriForey** [comment]
@florianthiery are you happy with the increased width?

**Comment by florianthiery** [comment]
can you take a screenshot and post it here? would be perfect :-) thx @TeriForey

**Comment by TeriForey** [comment]
Screenshot 2020-06-24 at 15 43 14

**Comment by florianthiery** [comment]
looks perfect!

**Pull request merged**
