### PR TITLE
Add Submission deadlines to calendar

### PR DESCRIPTION
**Pull request by Chilipp**
This PR adds the submission deadlines to the calendar. They appear as allDay events in the [calendar][calendar] and as one-shot events in the [upcoming events][upcoming].

[calendar]: https://527-267395254-gh.circle-artifacts.com/0/SORSE/programme/calendar/index.html
[upcoming]: https://527-267395254-gh.circle-artifacts.com/0/SORSE/index.html#upcoming-events

I also colored the events with the same color as the team-buttons and the submission deadline events also use a color from the logo.

From my perspective, this PR is ready to be merged. What do you think @vsoch?

### CODE REVIEW

**Comment by vsoch** [comment]
The plumbing looks okay, but it's fairly hard to read the text when you look at gray on yellow, e.g.,

image

I would say to either put a color coded legend somewhere around the calendar (this is actually what i looked for first, strangely enough) or adjust the colors so it's very obviously readable. After that, we should be good.

**Comment by Chilipp** [comment]
hmm, agreed. no idea how to change that color...

**Comment by vsoch** [comment]
I think the issue is opacities that are set for the title, e.g.,
```
.fc .fc-bg-event {
    background: rgb(143, 223, 130);
    background: var(--fc-bg-event-color, rgb(143, 223, 130));
    opacity: 0.3;
    opacity: var(--fc-bg-event-opacity, 0.3);
}
```
If you remove opacity there, then you can set the `.fc-event-title` to a black color and it actually looks black. If this color is going to be universal for submission deadlines, maybe it would be more straight forward to add a legend?

**Comment by vsoch** [comment]
Also note that some of the other nested /stacked divs there have an opacity set to a low value, I removed it for that one and one more (and of course I can't find it now!)

**Comment by Chilipp** [comment]
what do you think about this?

image

> it would be more straight forward to add a legend

sounds like a good idea. Can you do this? :sweat_smile:

**Comment by vsoch** [comment]
I don't have the bandwidth this week, but if you want to create an issue I can do it sometime in the future :) Personally I think your adjustment would be appropriate.

**Comment by Chilipp** [comment]
alright done: https://530-267395254-gh.circle-artifacts.com/0/SORSE/programme/calendar/index.html

**Pull request merged**
