### PR TITLE
HPC Champions Workshop

### PR DESCRIPTION
**Pull request by cc-a**
Ended up putting it as a standard workshop for now, only flagging as a partner event via the title. Suggest we review whether a separate category is appropriate for partner events in the future. Will invite input from event organisers before requesting a review.

### CODE REVIEW

**Comment by Chilipp** [comment]
Did you also make a submission to indico @cc-a to reserve the event id? See the invited contributions sections in https://docs.google.com/document/d/1EExW-DRT1bA4CxZYOC5xCbr5NpNJGTRLn4hPAr8v2Sg/edit?usp=drivesdk

**Comment by cc-a** [comment]
The [Indico event](https://indico.scc.kit.edu/e/hpc-champions-2020) has been up for a while.

**Comment by Chilipp** [comment]
Not sure if this is what we mean. What do you think @eileen-kuehn ?

**Comment by aniabrown** [comment]
Hi, I tweaked the speaker list and added the other speakers.

**Comment by cc-a** [comment]
@Chilipp  Ah wait, I know what you mean. Yes, this should be event no. 24 actually.

**Comment by cc-a** [comment]
Should be corrected and ready for review. Thanks @aniabrown

**Review by TeriForey — APPROVED** [review]
LGTM

**Pull request merged**
