### PR TITLE
Decrease member images

### LINKED ISSUE #200: reduce size of contact pictures
Some of the contact pictures on https://github.com/SORSE/sorse.github.io/tree/master/assets/images, at least for me and for Debbie Carter are quite large and take time to load in https://sorse.github.io/contact/ - they should probably be downscaled if they are just going to be used at this small size.

### PR DESCRIPTION
**Pull request by Chilipp**
this PR adds a script to downscale images of the committee members and downscales some of the images. Furthermore, I changed the /contact/ page to a wide layout.

The results can be seen in https://375-267395254-gh.circle-artifacts.com/0/SORSE/contact/index.html

It decreased the downloaded image data from 24MB (see https://github.com/SORSE/sorse.github.io/issues/200#issuecomment-650054492) to about 8MB (see screenshot below).

 

@vsoch: Could you please have a look at it? To me, all images looked fine

The following images have been downscaled:

- @florianthiery 
- @cc-a 
- Kirsty Pringle
- @alisonrclarke
- @teapowell
- @andrewgait
- @sandragesing
- @MarionBWeinzierl
- @louisepb
- @mmshad
- Debbie Carter
- @nrmay
- @nooriyahp
- @danielskatz
- @cosden

if nobody complains, I'll merge this PR Wednesday morning.

closes #200

### CODE REVIEW

**Comment by vsoch** [comment]
My quick critique is that this would require manually running it - who is going to do that and when? Any reason to not automate the downsizing?

**Comment by Chilipp** [comment]
no, just laziness :wink: shall we add a workflow to automatically downscale the images? Or what would you suggest?

**Comment by vsoch** [comment]
A scheduled task to run the script, and then open a PR with changes (at some frequency). If you can show me how to run the script, I can do a quick PR to this one.

**Comment by Chilipp** [comment]
sure, it's quite easy:

```bash
bash scripts/downscale_images.sh
```
The only dependency that needs to be installed is imagemagick.

I'd make a workflow that run's on every push to the master branch, i.e.
```yaml
on:
  push:
    branches:
      - master
```
wouldn't this make more sense than a scheduled one?

**Comment by vsoch** [comment]
@Chilipp if the repository is deployed on a different branch than master (e.g., gh-pages) then you could do that, and have a PR (or push) go to gh-pages. But if the repository is deployed to master, it would be an infinite loop to PR back to master and then trigger it again.

**Comment by vsoch** [comment]
That's why I was thinking of a scheduled task trigger instead - it would run once a week, and then open a PR with changes. That means that someone needs to review / merge once a week. It could also push directly to master, if you are comfortable with that.

**Comment by Chilipp** [comment]
> It could also push directly to master, if you are comfortable with that.

No, I'd go for a PR

> But if the repository is deployed to master, it would be an infinite loop to PR back to master and then trigger it again.

but if there are no images to downscale downscaled within the workflow, then there is no commit and as such no new PR will be opened. So this would not create an infinite loop, wouldn't it?

**Comment by vsoch** [comment]
Technically yes, but it makes me uneasy. I don't have a lot of trust for GitHub actions, so I try to avoid loops like that, in the chance they might be used in a way that I'm not aware of. But if you want me to open a PR to this branch with this strategy, I'd be happy to give it a shot. I'll also add empty pull_request as a temporary trigger so we can test it.

**Comment by Chilipp** [comment]
alright, no complains so I'll merge this

**Pull request merged**
