### PR TITLE
Highlight speakers

### PR DESCRIPTION
**Pull request by Chilipp**
Ok, one more thing that I almost forgot: The presenting authors (there might be multiple) need to be highlighted. This is done with this PR, see https://592-267395254-gh.circle-artifacts.com/0/SORSE/programme/workshops/event-004/index.html

I am a bit afraid that it might be too many icons in the author list, what do you think @vsoch?

### CODE REVIEW

**Comment by eileen-kuehn** [comment]
@Chilipp, it might help aligning the baselines of the icons.

**Comment by Chilipp** [comment]
you mean like this @eileen-kuehn? 

image

**Comment by vsoch** [comment]
yeah it's a bit busy! Can you remove the camera icon (it doesn't seem to do anything?) Does it add value?

**Comment by Chilipp** [comment]
it's showing who the presenting author(s). do you think highlighting in bold is enough already @vsoch ?

**Comment by vsoch** [comment]
Yes! I wouldn't have guessed that's what the camera icon indicated, I was thinking it meant along the lines of "a video recording is available." The other icons are meaningful (home page or orcid link or affiliation) so I wouldn't remove those.

**Comment by Chilipp** [comment]
I see, the alternative would the following:

image

where the presenting authors (_Workshop Guy_ and _Some Guy_) are formatted bold

**Comment by vsoch** [comment]
I think that works! Personally I don't think I'd care/ want to know who exactly is presenting when I'm reading the abstract, because it wouldn't impact my decision to register or not.But if you think it's important, the bold would do the trick. Another idea would be to create a special "affiliation" link for presenting authors (akin to how papers do corresponding authors).

**Comment by Chilipp** [comment]
> Another idea would be to create a special "affiliation" link for presenting authors (akin to how papers do corresponding authors).

Can you provide an example? From the top of my head I just know the case where the corresponding author is highlighted with a little email symbol next to his name.

**Comment by vsoch** [comment]
Sure! Like this:
image

**Comment by Chilipp** [comment]
ah ok, so this is actually not manipulating the affiliation, but rather adding a footnote to highlight the presenting authors. So it's the same that I did before, but adding a `*` instead of a camera symbol and explain it down below.

Sounds good to me! Shall we use a `*`, the camera symbol or a [little speech bubble](https://fontawesome.com/icons/comment?style=regular)?

**Comment by Chilipp** [comment]
a `*` is probably the best to make sure it doesn't get too many icons

**Comment by Chilipp** [comment]
done: https://595-267395254-gh.circle-artifacts.com/0/SORSE/programme/workshops/event-004/index.html

**Comment by Chilipp** [comment]
the test failure is just because of the dummy events. I'll fix this

**Comment by Chilipp** [comment]
alright, from my perspective this is ready to be merged

**Comment by Chilipp** [comment]
I'm going asleep now, so please merge it if you are okay with the result @vsoch 

Thanks for your helpful advice as always :smiley:

**Pull request merged**
