### PR TITLE
Schedule 15 9

### PR DESCRIPTION
**Pull request by catsmith**
This is the last session to be scheduled from existing submissions.

### CODE REVIEW

**Comment by Chilipp** [comment]
LGTM, thanks @catsmith. We just need the registration url from @eileen-kuehn here, too

**Comment by catsmith** [comment]
One of these has changed his mind about his availability, please could we keep this on hold until I figure out a solution.

**Comment by catsmith** [comment]
phew, quick solution found. Moving to Monday of the same week at the same time.

**Review by Chilipp — APPROVED** [review]

**Comment by Chilipp** [comment]
great! thanks @eileen-kuehn! The test failure is related to something that has already been solved in master, so we'll merge this and I update the google calendar

**Pull request merged**
