### PR TITLE
Update event-030.md

### PR DESCRIPTION
**Pull request by catsmith**

### CODE REVIEW

**Comment by catsmith** [comment]
@Chilipp I have added the times to everything which I have details for. Some are in the pull request for the round 5 events and there are two separate ones, this is the last of them.

@eileen-kuehn We need to an entry in the software demos events for abstract number 7 which was on the waiting list and is now scheduled. Once we have that there are three indico events that can be created. They are the ones on the scheduling spreadsheet for week beg. 11th, 25th Jan and 8th Feb. The 8th Feb one is the one missing abstract 7. 

Please let me know if you need any more details or I can do anything else to help with this.

**Comment by Chilipp** [comment]
thanks @catsmith! @eileen-kuehn, please let me know when you created the registration event on indico

**Comment by eileen-kuehn** [comment]
@catsmith, @Chilipp, I added event 7 and the times as well as the links to Indico. Should be ready now.

**Review by Chilipp — APPROVED** [review]
great, thanks!

**Comment by Chilipp** [comment]
I am just regenerating the PDF for event-007 and then we can merge this

**Pull request merged**
