### PR TITLE
add and show logo for event-028

### PR DESCRIPTION
**Pull request by Chilipp**
This PR adds the logo for the EESSI software demo (event 028, see https://sorse.github.io/programme/software-demos/event-028/)

### CODE REVIEW

**Comment by Chilipp** [comment]
Here is a preview

https://1499-267395254-gh.circle-artifacts.com/0/SORSE/programme/software-demos/event-028/index.html

**Comment by Chilipp** [comment]
@boegel, @alisonrclarke mentioned that you would like to see the EESSI-Logo on your events page. Please have a look at https://1507-267395254-gh.circle-artifacts.com/0/SORSE/programme/software-demos/event-028/index.html

If this is okay for you, we can merge this PR.

**Comment by boegel** [comment]
@Chilipp Thank you very much for looking into it!

I was more thinking of adding the logo on the page itself, for example just above the 2nd paragraph which starts with "`The European Environment for Scientific Software Installations (EESSI, ...`".

Is that an option too?

One downside of the EESSI logo is the small text, which is now unreadable when the logo is added as an "avatar".

**Comment by Chilipp** [comment]
sure @boegel, than it looks like this

https://1509-267395254-gh.circle-artifacts.com/0/SORSE/programme/software-demos/event-028/index.html

**Comment by boegel** [comment]
@Chilipp That's perfect as far as I'm concerned, thanks a lot!

**Comment by Chilipp** [comment]
you're welcome! Thanks for your contribution :+1:

**Pull request merged**
