### PR TITLE
Updated 019 to rescheduled time

### PR DESCRIPTION
**Pull request by catsmith**
This is ready to go live - I was trying to do them all in a single request but I can't see how.

### CODE REVIEW

**Comment by catsmith** [comment]
Please hold off on publishing this one for a while. I have just noticed a clash with the RSE AGM and have asked if there is another day we could run this.

**Comment by Chilipp** [comment]
alright @catsmith, I changed this to a draft PR. Make it ready for review again when you are happy with the timing (and consider that you need to change the format how you add the times, see https://github.com/SORSE/sorse.github.io/pull/288#discussion_r477546965

**Comment by catsmith** [comment]
I'm not sure how to remove the work in progress but this is now ready to go and I think I fixed the problem with the formatting as well.

**Review by Chilipp — APPROVED** [review]
thanks @catsmith!

**Pull request merged**
