### PR TITLE
fix time and authorlist for HPC workshop event-024

### PR DESCRIPTION
**Pull request by Chilipp**
this PR fixes the times for the HPC workshop

@aniabrown, could you just post the changes for the author list here or make a comment directly in the file via a suggestion?

### CODE REVIEW

**Comment by cc-a** [comment]
Sorry @Chilipp one more correction to the times. Should be 12:00 UTC to 16:00 UTC.

**Comment by Chilipp** [comment]
@aniabrown: could you please quickly review https://1278-267395254-gh.circle-artifacts.com/0/SORSE/programme/workshops/event-024/index.html and tell me whether everything is okay?

**Comment by Chilipp** [comment]
just for completeness: the PDF now looks like https://1282-267395254-gh.circle-artifacts.com/0/SORSE/downloads/event-024.pdf

**Comment by aniabrown** [comment]
That looks good now -- thanks very much for making the changes!

**Pull request merged**
