### PR TITLE
Added new Sponsorship page

### LINKED ISSUE #124: 'For delegates' broken
'For delegates' button at top right pf page takes you to page not found.

### LINKED ISSUE #150: new page - Sponsorship
web team - this doesn't have to be in a bullet opint list if you think a table would look better? 

------
The SORSE committee is looking for sponsors to partner with us and get involved in delivering this series of events to the international RSE community. These sponsorship packages are valid for 6 months from the 1st July 2020 to December 2020. 

Get in touch with the Sponsorship Team, Claire and Max via sorse.enquiries@gmail.com 

The Exa and Peta packages can choose from one of these perks:
- VM/Cloud for workshops
- Award a Poster Prize (each poster session)
- Translation Services
- Subtitles services
- Host archiving of resources (TIB-AV)

**Exa - £5,000**

- 1 sponsored talks, workshops, software demo, panel at some point over the six months
- Sponsor of a guest speaker (chosen by the programme team)
- Virtual networking zoom breakout room, activated after the event, 1 a month
- Blog post to the RSE Community on the SORSE website
- Tweet mentioning sponsorship from SORSE twitter account
- Access to registration data from ‘Opt-in’ attendees 
- Logo included in sponsorship slide at beginning of each event
- Logo, company description and link on the SORSE website 
- Mention in the opening session of the series

**Peta - £3,000**

- 1 sponsored talks, workshops, software demo, panel at some point over the six months
- Virtual networking zoom breakout room, activated after the event, 1 a month
- One chosen perk (list below)
- Blog post to the RSE Community on the SORSE website
- Tweet mentioning sponsorship from SORSE twitter account
- Access to registration data from ‘Opt-in’ attendees 
- Logo included in sponsorship slide at beginning of each event
- Logo, company description and link on the SORSE website 
- Mention in the opening session of the series

**Terra - £1,000**

1 x sponsored poster
Virtual networking zoom breakout room, activated after the event, 1 a month
Blog post to the RSE Community on the SORSE website
Tweet mentioning sponsorship from SORSE twitter account
Access to registration data from ‘Opt-in’ attendees 
Logo included in sponsorship slide at beginning of each event
Logo, company description and link on the SORSE website 
Mention in the opening session

**Giga - £500**
Aimed at Open Source initiatives, charities and foundations

- 1 x sponsored poster
- Blog post to the RSE Community on the SORSE website
- Tweet mentioning sponsorship from SORSE twitter account
- Access to registration data from ‘Opt-in’ attendees 
- Logo included in sponsorship slide at beginning of each event
- Logo, company description and link on the SORSE website 
- Mention in the opening session

### PR DESCRIPTION
**Pull request by eileen-kuehn**
This PR adds a new page for sponsorship as mentioned in #150.
As I consider the sponsorship important at the moment, I added it to the top menu instead of the *Delegates* link. This was expected to be removed given comments in #124. If this is ok, we can also close #124.
The left menu style follows FAQ at the moment as I consider this to be relevant for a potential sponsor :)

Screenshot 2020-06-23 at 20 15 16

Please leave your comments, we can change those things anytime!

This PR closes #150.

### CODE REVIEW

**Comment by eileen-kuehn** [comment]
@Chilipp,  great idea! Will do so immediately :)

**Comment by sdruskat** [comment]
Fixed that typo, you're just too hip @ClaireWyatt ;)

**Comment by sdruskat** [comment]
Hard merge, build hangs.

**Comment by eileen-kuehn** [comment]
> The title is missing an 's' should be 'Sponsorship' (probably my typo)

Could have been me. My keyboard is very buggy with *space* and *s* at the moment :/

**Pull request merged**
