### PR TITLE
Split test and build into two jobs

### PR DESCRIPTION
**Pull request by Chilipp**
This small PR does two changes:

1. It separates the url tests from building the site and uploading artifacts (testing takes longer and fails sometimes, then we can immediately see, where the problem is)
2. it removes the `baseurl` and `url` keys from `_config.yml` as they are actually not necessary and including them makes it impossible to host this repo using Github pages in a fork

@vsoch: Are you okay with these changes?

### CODE REVIEW

**Comment by vsoch** [comment]
The changes are ok with me! The true validation is if the tests work as you want, so when those pass and you've confirmed that, I think we're good for merge.

**Comment by vsoch** [comment]
I'm not sure why but I can't actually click on the build check to see it in action.

image

**Comment by Chilipp** [comment]
hmm, good point. nothing started on circleci, see https://app.circleci.com/pipelines/github/SORSE/sorse.github.io, only on my personal account https://app.circleci.com/pipelines/github/Chilipp/sorse.github.io

**Comment by Chilipp** [comment]
I just checked, building of forked PRs is enabled
image

I'll close this PR and reopen it. This should trigger the CI again. Maybe circle has a problem...

**Comment by Chilipp** [comment]
just changed the branch protection rule to not make the circleCI tests required. So closing and reopening again. If this does not help, I'll try again in a couple of minutes

**Comment by Chilipp** [comment]
ok, found the reason: https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

**Comment by Chilipp** [comment]
just unfollowed the project of my fork on CircleCI and (again), closing and reopening this PR

**Comment by vsoch** [comment]
When this has happened to me before it has been one of three things:
 - bug with circle (or just being down, waiting might resolve)
 - bug in my recipe that resulted in no jobs running

So - you just refreshed the connection to debug part of 1, and if that doesn't work we can wait (to see if it's ephemeral) or try changing the recipe to see if it's an issue with triggers.

**Comment by Chilipp** [comment]
worked! So the reason was that I enabled the project in my own CircleCI config. I had to unfollow it there...

**Comment by vsoch** [comment]
ahhh a fourth thing! So many :bug:

**Comment by Chilipp** [comment]
alright! seemed to work: https://github.com/SORSE/sorse.github.io/runs/823728892

**Comment by Chilipp** [comment]
@vsoch, feel free to approve and merge this PR if it looks okay for you :smiley:

**Comment by vsoch** [comment]
Can we update the branch from master?

**Comment by Chilipp** [comment]
you mean, merge the master of https://github.com/SORSE/sorse.github.io into this fork?

**Comment by vsoch** [comment]
I copied the image that I see for this PR - do you not see that message (a gray button, and then a prompt to "Update branch?")

**Comment by Chilipp** [comment]
sure, done. Sorry, the image was not shown in the mail I got.

I also just removed the branch protection rule that made this a requirement (it has accidentaly been activated)

**Pull request merged**
