### PR TITLE
Fix PDF generation

### PR DESCRIPTION
**Pull request by Chilipp**
This PR tackles several PDF generation issues using the github workflow.

1. several formatting issues caused encoding problems (see a4031b2, ping @eileen-kuehn)
2. the PDF generation failed when the entries did not have an associated doi (because `ob-paper get ....md doi` fails), therefore I removed it (3d96c4e)
3. the year wasn't displayed because it was not in the meta data (should have been taken from the date, see c955b6b, 42a5d9a180b713cfd94acb664f71a7494568aafb)

there are still some issues left:

- [x] multiple authors and not shown in the author list 
- [x] affiliations are not shown 
     1. it should be `$authors.bio$` instead of `$authors.affiliation$` (due to minimal-mistakes, maybe we should change this however) in [author-profile.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/author-profile.html)
     2. we don't have an `$affiliations$` variable available in the template

### CODE REVIEW

**Comment by eileen-kuehn** [comment]
Short question regarding the encoding issues. N-dashs were replaced by ``&ndash;`` whereas & was substituted to ``and`` instead of ``&amp;``.  I think this would also work for the smart quotes, e.g. ``&ldquo;``? I would like to make it consistent. Do you foresee any issues?

**Comment by Chilipp** [comment]
`&ldquo;` is fine. 

The `&` is a different story: If we have an `&` or `&amp;` in the `title`, it would need to be escaped in latex, because otherwise the PDF compilation fails. So replacing it with `and` was the easier solution :sweat_smile:

**Comment by eileen-kuehn** [comment]
Ok, then I will take care to have different replacements based on the section we are talking about.

**Comment by Chilipp** [comment]
@trallard: Do you have a higher-resolution logo that is more suited to be embed in a PDF? The current one (135x50) is a too lowres. Something with a width of 1000px would be ideal.

image

**Comment by Chilipp** [comment]
A PDF file would actually be the best @trallard

**Comment by trallard** [comment]
Sorted! And sent to @Chilipp

**Comment by Chilipp** [comment]
thanks a lot @trallard!

**Pull request merged**
