### PR TITLE
Update event-014.md

### PR DESCRIPTION
**Pull request by andrewgait**
Add link to slides for event-014.

### CODE REVIEW

**Comment by Chilipp** [comment]
LGTM https://1387-267395254-gh.circle-artifacts.com/0/SORSE/programme/talks/event-014/index.html

The test failure is not related to this issue

**Review by Chilipp — APPROVED** [review]

**Comment by Chilipp** [comment]
@andrewgait, can we merge this then?

**Comment by andrewgait** [comment]
Yes - go ahead and merge it.

**Comment by andrewgait** [comment]
Actually - wait, I've just realised I can add the PDF to the indico page.  I'll do that instead later this afternoon.

**Comment by andrewgait** [comment]
OK, ready to merge now.

**Comment by Chilipp** [comment]
Thanks @andrewgait !

**Pull request merged**
