### PR TITLE
Adding Zoom URL

### PR DESCRIPTION
**Pull request by eileen-kuehn**
This PR adds the `meeting_url` for todays event.

### CODE REVIEW

**Review by Chilipp — APPROVED** [review]

**Comment by Chilipp** [comment]
sorry, I was a bit too fast with approving. Seems like the join button is not displayed

https://1174-267395254-gh.circle-artifacts.com/0/SORSE/programme/software-demos/event-019/index.html

**Comment by eileen-kuehn** [comment]
Hm... maybe an issue about time zones... I will have a look.

**Comment by eileen-kuehn** [comment]
Two issues here:

* we had whitespace and couldn't therefore properly compare the timestamps, and
* timestamp in javascript was in milliseconds.

These issues are fixed now.

**Comment by Chilipp** [comment]
awesome! looks good to me :+1:

**Comment by Chilipp** [comment]
the remaining CI failure is fixed by #328, so let's merge this :)

**Pull request merged**
