### PR TITLE
Links to indico events

### PR DESCRIPTION
**Pull request by eileen-kuehn**
This PR adds the links to the specific Indico events for registration of all events that are successfully scheduled already.

Please note: I created one single event in case two contributions are scheduled one after the other, so participants only need to register once.

### CODE REVIEW

**Review by Chilipp — APPROVED** [review]
LGTM! Thanks @eileen-kuehn :smiley:

**Comment by Chilipp** [comment]
As a side note: it seems like the indico registration is not well suited for mobile devices. The text reads good but the registration button is incredibly small

**Comment by Chilipp** [comment]
Feel free to merge this when you are happy with it @eileen-kuehn

**Comment by eileen-kuehn** [comment]
> As a side note: it seems like the indico registration is not well suited for mobile devices. The text reads good but the registration button is incredibly small

Good to know, thanks! We could even directly link to the registration itself, you only need to append `registrations` to the `registration_url`.

**Pull request merged**
