### PR TITLE
Add/url checker

### PR DESCRIPTION
**Pull request by vsoch**
This is a first shot at adding the urlchecker-action as a GitHub workflow to run for the site. I've not actually used it with a jekyll site, so it might take me a few tries to get the setup correct, and then we will likely need to discuss urls to be whitelisted, etc.

### CODE REVIEW

**Comment by vsoch** [comment]
okay! urlchecker ran here https://github.com/SORSE/sorse.github.io/pull/183/checks?check_run_id=804056547 and it looks like the following urls have issues. Linked in is usually spotty because it has that loading screen - so I think we should whitelist. As for the .be address, it's a certificate failure, so we don't have any choice but to whitelist.

https://rse-leaders.github.io/SORSE20/programme/bazaar/#submit
https://u0052546.pages.gitlab.kuleuven.be/images/avatar.jpg
https://u0052546.pages.gitlab.kuleuven.be/
https://www.linkedin.com/in/simon-hettrick-2668a9a/

I do think, however that this one should work -

https://rse-leaders.github.io/SORSE20/programme/bazaar/#submit

**Comment by vsoch** [comment]
Found the correct bazaar page! https://sorse.github.io/programme/bazaar/#submit

**Comment by vsoch** [comment]
One more error, not sure what this link is for but it's failing all retries and extended timeout:

```
 https://browsehappy.com/
HTTPSConnectionPool(host='browsehappy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6ad301a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
https://browsehappy.com/
HTTPSConnectionPool(host='browsehappy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6ad317670>: Failed to establish a new connection: [Errno 111] Connection refused'))
https://browsehappy.com/
```

**Comment by Chilipp** [comment]
> One more error, not sure what this link is for but it's failing all retries and extended timeout:

where does this appear @vsoch? It's not in the files when I build it locally

**Comment by vsoch** [comment]
@Chilipp it's a part of minimal-mistakes: https://github.com/mmistakes/minimal-mistakes/blob/fc3e7a61769253f10d325525b0a7a334166f49ac/_includes/browser-upgrade.html

You know, what we might want to do (to both speed up the test and not have the redundancy that comes from these links on several pages) is just to test our static files (before a jekyll build). That way we don't test minimal-mistakes templating, but rather just the files we have added (links in .yaml, python, markdown, etc.). That also means we don't need to install jekyll and build the site, so it would be much faster. What do you think?

**Comment by Chilipp** [comment]
But then we don't test internal links and whether they resolve correctly, don't we?

**Comment by vsoch** [comment]
What is an internal link?

**Comment by vsoch** [comment]
If a link looks like:
```
<script src="/assets/js/lunr/lunr-en.js"></script>
```
then it's not going to match a pattern for a url so it wouldn't be checked.

**Comment by Chilipp** [comment]
no, sorry, I rather mean something like `<a href="{{ site.data.committee.programme_teams.talks.internal }}">`

**Comment by Chilipp** [comment]
i.e. where the link is constructed using jekyll

**Comment by vsoch** [comment]
Ah right, so if that renders to not start with https (I guess an external link) it won't be tested, so probably urlchecker isn't the right tool. Sorry for wasting your time.

**Pull request closed without merging**
