### PR TITLE
Update event-017.md

### PR DESCRIPTION
**Pull request by catsmith**
I've added the times for the workshop. It will be run twice so this is our first example of a repeat. I also added last_modified_at:

### CODE REVIEW

**Comment by Chilipp** [comment]
alright, thanks @catsmith. I did not yet find the time to implement this in the website, sorry. I'll do my best to do it this evening

**Comment by Chilipp** [comment]
@eileen-kuehn, will we have one Indico event for registration per slot?

**Comment by eileen-kuehn** [comment]
@Chilipp, I was also asking this and I think @catsmith said no. So I currently created one event that aggregates the contributions of that day. So one registration can be for several contributions.

**Comment by catsmith** [comment]
@eileen-kuehn, @Chilipp I was thinking of a different scenario when I said no. That was two half hour papers scheduled for the same hour. This is the same event scheduled twice (the same content repeated for different time zones).

**Comment by eileen-kuehn** [comment]
@catsmith, @Chilipp, ah sorry, I understood the question in a wrong way.
Yes, we will have different event registration links per time slot (I was considering sequential contributions in one event that share the same URL).

**Comment by Chilipp** [comment]
alright thanks @eileen-kuehn. Then we need a way to display the two of them on the event page

**Review by Chilipp — APPROVED** [review]

**Pull request merged**
