### PR TITLE
Contributions from first round of call for abstracts

### PR DESCRIPTION
**Pull request by eileen-kuehn**
This PR adds the metadata for accepted contributions from the first round of call for abstracts.

### CODE REVIEW

**Comment by Chilipp** [comment]
Great! Thanks a lot @eileen-kuehn. We'll have to merge #223 first to make this work. From my perspective, #223 can be merged but I just did want to give others the possibility to review it. If there is no negative reaction, I think I'll just merge it this evening. Or is there any rush to publish these today on our website?

**Comment by eileen-kuehn** [comment]
@Chilipp, no, there is no rush from my side. Just wanted to minimise my todo-list a bit that I can focus on all the other tasks that are still waiting ;) So please take your time.

**Comment by Chilipp** [comment]
we have to change the name of `software_demos` into `software-demos`. Otherwise we have inconsistent paths on the website (I forgot to do by myself and just did this for the dummy events in 2f40df3). I'll do this quickly

**Comment by eileen-kuehn** [comment]
Ok, I will adapt that it will work in future PRs.

**Comment by eileen-kuehn** [comment]
> we have to change the name of `software_demos` into `software-demos`. Otherwise we have inconsistent paths on the website (I forgot to do by myself and just did this for the dummy events in [2f40df3](https://github.com/SORSE/sorse.github.io/commit/2f40df3f98d976ea389ee536815c3696d0cb8c87)). I'll do this quickly

One question regarding the renaming, is the ``category`` field still consistent? So is this also set to ``software-demo`` instead of ``software_demo``? Thanks!

**Comment by Chilipp** [comment]
it's `software_demo`, see https://github.com/SORSE/sorse.github.io/blob/master/_data/committee/programme_teams.yml. Yes, I know, it's not nice. shall we change it? I actually don't like the fact that the webpages are plural (`/programme/talks/`) and the identifier is singular (`talk`), too.

**Comment by eileen-kuehn** [comment]
Hm, I actually don't care. We just have to define it. However, consistent naming would be great as this might reduce mistakes in linking and so on. Just make a decision and you will get the data as required :)

**Comment by Chilipp** [comment]
alright, give me a sec

**Comment by Chilipp** [comment]
closing this in favor of #245

**Pull request closed without merging**
