### PR TITLE
update my own topic bazaar item

### PR DESCRIPTION
**Pull request by florianthiery**
RSEs in the Digital Humanties or archaeological domain

### CODE REVIEW

**Comment by TeriForey** [comment]
Are you adding a link to your own pad that is separate from the topic bazaar?

**Comment by florianthiery** [comment]
if we want to link to a general one I am fine with that also :-) @TeriForey

**Comment by florianthiery** [comment]
I just thought about how to organize the group somehow, but if you have a generic idea @TeriForey I am fine with that :-)

**Comment by TeriForey** [comment]
Totally okay with your organising your own pad and group, in fact it sounds like a great idea 👍 

But, could you make the text a little clearer that it's for your own group submission? When I first read it I was a little confused which is why I asked that question :)

**Comment by florianthiery** [comment]
sth like this @TeriForey ?

**Comment by florianthiery** [comment]
but I cannot merge it :-) @TeriForey

**Pull request merged**
