### PR TITLE
Add/calendar button

### PR DESCRIPTION
**Pull request by Chilipp**
As a follow-up of #228, this PR adds the add-calendar-button to the event pages

here we add a submodule of https://github.com/SORSE/add-to-calendar-buttons and some custom styling to match our theme.

The result can be seen here: https://572-267395254-gh.circle-artifacts.com/0/SORSE/programme/workshops/event-004/index.html

Any comments @vsoch?

### CODE REVIEW

**Comment by Chilipp** [comment]
the remaining test-failures are due to external urls.

researchsoftware.org seems to be down again but we actually decided to remove it and create our own blog, so I'll remove it now

**Comment by Chilipp** [comment]
alright, I am done here @vsoch, this is ready to be reviewed

**Comment by Chilipp** [comment]
Hmm, @vsoch: currently this button is also added to the cards in `/programme/` (see https://572-267395254-gh.circle-artifacts.com/0/SORSE/programme/index.html). We have two options here:

1. remove the buttons from the cards
2. do not make the entire card clickable

Because currently, when you click on a button in a card, it opens the event in a separate tab and displays the dropdown button.

Which option do you prefer? I'd tend to option 2

**Comment by vsoch** [comment]
I think I prefer 1, but I don't feel strongly about it.

**Comment by Chilipp** [comment]
Done: https://580-267395254-gh.circle-artifacts.com/0/SORSE/programme/index.html

**Pull request merged**
